# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Zeeshan Akram
title: Software Engineer
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  zeeshanakram3
stackoverflow_username: "10427850"
linkedin_username: mzeeshanakram

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Zeeshan. I am BS Computer Science graduate and a software engineer working in Blockchain space.  I am primarily interested in distributed systems and computer networks, and consesus algorithms. I love researching about Blockchain and how its shaping the internet and the financial systems.

  **Technologies**: Golang, Rust, Node.js, Clarity, NEAR, Solidity, Gqlgen, AWS, Docker, Terraform, CircleCI 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: NFT Marketplace on NEAR
        additional_links:
          - title: https://github.com/zeeshanakram3/near-blockchain-smartcontracts
            icon: fab fa-github
            url: https://github.com/zeeshanakram3/near-blockchain-smartcontracts
        description: |
          Created Dapps, Social coins, NFTs, NFT marketplace, and content-based NFT protocols on the NEAR blockchain using Rust targeting WASM VM.
      - layout: top-middle
        title: Analyzing Newly Listed Cryptoassets
        additional_links:
          - title: https://github.com/zeeshanakram3/trading 
            icon: fab fa-github
            url: https://github.com/zeeshanakram3/trading 
        description: | 
          Created a project for analyzing tading data of newly listed coins on messari.io, coinmarketcap, and coingeko for making effecient trading decisions.
      - layout: top-middle
        title: Tor Research Project
        description: | 
          Collected and Analyzed data pertinent to ads served on Alexa top 500 sites; studied different characteristics of ads such as language, area served, target audience, etc. Examined the impact of different Circumvention mechanisms on the online advertising system. Devised a mechanism to serve geographically relevant ads to users in Tor Browser without undermining their anonymity.      
      - layout: top-middle
        title: Emulating impact of EVs
        description: |
          Devised an optimal night scheduling solution for electric vehicle charging by analyzing LESCO last six months of Grid Load data, available at the granularity of 15 mins; devised different Machine Learning and Regression techniques in R to better forecast energy usage; the model predicted household electricity usage with 97% accuracy.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Software Engineer(Blockchian)
        sub_title: Tintash
        caption: July 2021 - Continue
        description: | # this will include new lines to allow paragraphs
          Working as Blockchain engineer creating dapps on Stacks Blockchain ecosystem using Clarity language.
      - layout: left
        title: Lucidspring Inc.
        sub_title: Software Engineer
        caption: August 2020 - July 2021 
        description: | # this will include new lines to allow paragraphs
          Developed both monolith and microservices applications in Golang, deployed them on AWS using Lambda, API Gateway, EC2. Worked on Rest and Graphql APIs.Worked as a blockchain developer. Developed dapps on NEAR protocol and Solana using Rust.Technologies: Golang, Rust, AWS, Terraform, Circleci, Graphql, Gqlgen
      - layout: left
        title: Remote Work
        sub_title: Software Engineer 
        caption: June 2019 - July 2020 
        description: | # this will include new lines to allow paragraphs
          I worked as a full-stack Web Developer in the MERN stack. I developed several web apps and interactive front-end components. Technologies: Node.js, React, MongoDB, Postgres  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Lahore University of Management Sciences
        sub_title: BS Computer Science
        caption: 2015 - 2019
     #   quote: >
        description: | # this will include new lines to allow paragraphs
         Relevant Courses:
          - Advanced Programming
          - Network Security
          - Topics in Internet Research
          - Deep Learning
          - Principles and Techniques of Data Science
          - Operating Systems
          - Databases
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Blockchain and software engineering some of my interests/hobbies are:
       - Table tennis
       - Community service
       - Crypto trading

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
